### ISSUE TITLE
xray makes import_data fail

### ISSUE THREAD

**Issue by peerjako-aws** [aws-samples/reinvent2018-dev303-code#21]
The import_data method in the catalog service seems to fail due to xray SegmentNotFoundException.

I managed to fix it locally by adding a begin_segment / end_segment like this: 
xray_recorder.begin_segment(name="import_data")

...

end_segment

**Comment by ckassen** [comment]
I'll take a look at this.

**Comment by ckassen** [comment]
I'm in the process of updating the project and will remove the import command. I have created a PR #23 and will run through tests to ensure everything is working fine.

**Comment by ckassen** [comment]
I've fixed this with #23
