### ISSUE TITLE
kubectl client version issue

### ISSUE THREAD

**Issue by gsingh04** [aws-samples/reinvent2018-dev303-code#22]
You must use a kubectl version that is within one minor version difference of your cluster. For example, a v1.2 client should work with v1.1, v1.2, and v1.3 master. Using the latest version of kubectl helps avoid unforeseen issues. [[details here]](https://kubernetes.io/docs/tasks/tools/install-kubectl/#before-you-begin)

**for eg. to update to version 1.15**
```
sudo curl --silent --location -o /usr/local/bin/kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
sudo chmod +x /usr/local/bin/kubectl
```

**Comment by ckassen** [comment]
Thanks for the hint. I'll update the instructions once I merge #23

**Comment by ckassen** [comment]
Updated the instructions to install newer kubectl
